[package]
name = "bedrock_sso_proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.27"
aws-sdk-bedrockruntime = "1.0"
aws-config = "1.0"
jsonwebtoken = "9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures-util = "0.3"
config = "0.15"
clap = { version = "4.0", features = ["derive"] }
