use axum::{
    body::Body,
    http::{Request, StatusCode},
};
use bedrock_sso_proxy::{
    auth::{api_key::CreateApiKeyRequest, jwt::JwtService},
    config::Config,
    database::entities::UserRecord,
    server::Server,
};
use chrono::Utc;
use tower::ServiceExt;

async fn create_test_server() -> Server {
    let mut config = Config::default();
    config.storage.redis.enabled = false;
    config.storage.database.enabled = true;
    config.storage.database.url = "sqlite::memory:".to_string();
    config.metrics.enabled = false;
    config.api_keys.enabled = true;

    let server = Server::new(config).await.unwrap();
    
    // Run database migrations to create tables
    server.database.migrate().await.unwrap();
    
    server
}

async fn create_test_user(server: &Server, email: &str) -> i32 {
    let user = UserRecord {
        id: 0, // Will be auto-generated by database
        provider_user_id: format!("test_user_{}", email.replace(['@', '.'], "_")),
        provider: "test".to_string(),
        email: email.to_string(),
        display_name: Some("Test User".to_string()),
        created_at: Utc::now(),
        updated_at: Utc::now(),
        last_login: Some(Utc::now()),
    };
    server.database.users().upsert(&user).await.unwrap()
}

fn create_test_jwt(jwt_service: &JwtService, user_id: i32) -> String {
    let claims = bedrock_sso_proxy::auth::jwt::OAuthClaims::new(user_id, 3600);
    jwt_service.create_oauth_token(&claims).unwrap()
}

#[tokio::test]
async fn test_api_key_authentication_with_authorization_header() {
    let server = create_test_server().await;
    let user_id = create_test_user(&server, "test1@example.com").await;
    let app = server.create_app();

    // First, create an API key via JWT authentication
    let jwt_token = create_test_jwt(&server.jwt_service, user_id);
    let create_request = CreateApiKeyRequest {
        name: "Test API Key".to_string(),
        expires_in_days: Some(30),
    };

    let request = Request::builder()
        .uri("/api/keys")
        .method("POST")
        .header("Authorization", format!("Bearer {}", jwt_token))
        .header("Content-Type", "application/json")
        .body(Body::from(serde_json::to_string(&create_request).unwrap()))
        .unwrap();

    let response = app.clone().oneshot(request).await.unwrap();
    assert_eq!(response.status(), StatusCode::OK);

    let body = axum::body::to_bytes(response.into_body(), usize::MAX)
        .await
        .unwrap();
    let create_response: bedrock_sso_proxy::auth::api_key::CreateApiKeyResponse =
        serde_json::from_slice(&body).unwrap();

    let api_key = create_response.key;
    assert!(api_key.starts_with("SSOK_"));

    // Now test using the API key to access Bedrock API
    let bedrock_request = Request::builder()
        .uri("/bedrock/model/anthropic.claude-sonnet-4-20250514-v1:0/invoke")
        .method("POST")
        .header("Authorization", format!("Bearer {}", api_key))
        .header("Content-Type", "application/json")
        .body(Body::from(r#"{"anthropic_version": "bedrock-2023-05-31", "max_tokens": 100, "messages": [{"role": "user", "content": "Hello"}]}"#))
        .unwrap();

    let response = app.oneshot(bedrock_request).await.unwrap();
    // Should not be unauthorized (would get 401 if API key auth failed)
    // Note: Will get 500 or other error due to AWS not being configured, but not 401
    assert_ne!(response.status(), StatusCode::UNAUTHORIZED);
}

#[tokio::test]
async fn test_api_key_authentication_with_x_api_key_header() {
    let server = create_test_server().await;
    let user_id = create_test_user(&server, "test2@example.com").await;
    let app = server.create_app();

    // First, create an API key via JWT authentication
    let jwt_token = create_test_jwt(&server.jwt_service, user_id);
    let create_request = CreateApiKeyRequest {
        name: "Test X-API-Key".to_string(),
        expires_in_days: Some(30),
    };

    let request = Request::builder()
        .uri("/api/keys")
        .method("POST")
        .header("Authorization", format!("Bearer {}", jwt_token))
        .header("Content-Type", "application/json")
        .body(Body::from(serde_json::to_string(&create_request).unwrap()))
        .unwrap();

    let response = app.clone().oneshot(request).await.unwrap();
    assert_eq!(response.status(), StatusCode::OK);

    let body = axum::body::to_bytes(response.into_body(), usize::MAX)
        .await
        .unwrap();
    let create_response: bedrock_sso_proxy::auth::api_key::CreateApiKeyResponse =
        serde_json::from_slice(&body).unwrap();

    let api_key = create_response.key;

    // Test using X-API-Key header instead of Authorization header
    let anthropic_request = Request::builder()
        .uri("/anthropic/v1/messages")
        .method("POST")
        .header("X-API-Key", &api_key)
        .header("Content-Type", "application/json")
        .body(Body::from(r#"{"model": "claude-sonnet-4-20250514", "max_tokens": 100, "messages": [{"role": "user", "content": "Hello"}]}"#))
        .unwrap();

    let response = app.oneshot(anthropic_request).await.unwrap();
    // Should not be unauthorized (would get 401 if API key auth failed)
    assert_ne!(response.status(), StatusCode::UNAUTHORIZED);
}

#[tokio::test]
async fn test_invalid_api_key_authentication() {
    let server = create_test_server().await;
    let app = server.create_app();

    // Test with invalid API key
    let request = Request::builder()
        .uri("/bedrock/model/anthropic.claude-sonnet-4-20250514-v1:0/invoke")
        .method("POST")
        .header("Authorization", "Bearer SSOK_invalid_key_12345678")
        .header("Content-Type", "application/json")
        .body(Body::from(r#"{"anthropic_version": "bedrock-2023-05-31", "max_tokens": 100, "messages": [{"role": "user", "content": "Hello"}]}"#))
        .unwrap();

    let response = app.oneshot(request).await.unwrap();
    assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
}

#[tokio::test]
async fn test_api_key_disabled() {
    let mut config = Config::default();
    config.storage.redis.enabled = false;
    config.storage.database.enabled = true;
    config.storage.database.url = "sqlite::memory:".to_string();
    config.metrics.enabled = false;
    config.api_keys.enabled = false; // Disable API keys

    let server = Server::new(config).await.unwrap();
    
    // Run database migrations to create tables
    server.database.migrate().await.unwrap();
    
    let app = server.create_app();

    // Test with API key when disabled
    let request = Request::builder()
        .uri("/bedrock/model/anthropic.claude-sonnet-4-20250514-v1:0/invoke")
        .method("POST")
        .header("Authorization", "Bearer SSOK_some_key_12345678")
        .header("Content-Type", "application/json")
        .body(Body::from(r#"{"anthropic_version": "bedrock-2023-05-31", "max_tokens": 100, "messages": [{"role": "user", "content": "Hello"}]}"#))
        .unwrap();

    let response = app.oneshot(request).await.unwrap();
    assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
}

#[tokio::test]
async fn test_revoked_api_key_authentication() {
    let server = create_test_server().await;
    let user_id = create_test_user(&server, "test3@example.com").await;
    let app = server.create_app();

    // Create an API key
    let jwt_token = create_test_jwt(&server.jwt_service, user_id);
    let create_request = CreateApiKeyRequest {
        name: "Test Revoke Key".to_string(),
        expires_in_days: Some(30),
    };

    let request = Request::builder()
        .uri("/api/keys")
        .method("POST")
        .header("Authorization", format!("Bearer {}", jwt_token))
        .header("Content-Type", "application/json")
        .body(Body::from(serde_json::to_string(&create_request).unwrap()))
        .unwrap();

    let response = app.clone().oneshot(request).await.unwrap();
    let body = axum::body::to_bytes(response.into_body(), usize::MAX)
        .await
        .unwrap();
    let create_response: bedrock_sso_proxy::auth::api_key::CreateApiKeyResponse =
        serde_json::from_slice(&body).unwrap();

    let api_key = create_response.key;
    let key_id = create_response.id;

    // Revoke the API key
    let revoke_request = Request::builder()
        .uri(format!("/api/keys/{}", key_id))
        .method("DELETE")
        .header("Authorization", format!("Bearer {}", jwt_token))
        .body(Body::empty())
        .unwrap();

    let response = app.clone().oneshot(revoke_request).await.unwrap();
    assert_eq!(response.status(), StatusCode::OK);

    // Try to use the revoked API key
    let test_request = Request::builder()
        .uri("/bedrock/model/anthropic.claude-sonnet-4-20250514-v1:0/invoke")
        .method("POST")
        .header("Authorization", format!("Bearer {}", api_key))
        .header("Content-Type", "application/json")
        .body(Body::from(r#"{"anthropic_version": "bedrock-2023-05-31", "max_tokens": 100, "messages": [{"role": "user", "content": "Hello"}]}"#))
        .unwrap();

    let response = app.oneshot(test_request).await.unwrap();
    assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
}

#[tokio::test]
async fn test_dual_authentication_support() {
    let server = create_test_server().await;
    let user_id = create_test_user(&server, "test4@example.com").await;
    let app = server.create_app();

    // Test JWT authentication still works
    let jwt_token = create_test_jwt(&server.jwt_service, user_id);
    let jwt_request = Request::builder()
        .uri("/bedrock/model/anthropic.claude-sonnet-4-20250514-v1:0/invoke")
        .method("POST")
        .header("Authorization", format!("Bearer {}", jwt_token))
        .header("Content-Type", "application/json")
        .body(Body::from(r#"{"anthropic_version": "bedrock-2023-05-31", "max_tokens": 100, "messages": [{"role": "user", "content": "Hello"}]}"#))
        .unwrap();

    let response = app.clone().oneshot(jwt_request).await.unwrap();
    // Should not be unauthorized (would get 401 if JWT auth failed)
    assert_ne!(response.status(), StatusCode::UNAUTHORIZED);

    // Create and test API key authentication
    let create_request = CreateApiKeyRequest {
        name: "Dual Auth Test".to_string(),
        expires_in_days: Some(30),
    };

    let request = Request::builder()
        .uri("/api/keys")
        .method("POST")
        .header("Authorization", format!("Bearer {}", jwt_token))
        .header("Content-Type", "application/json")
        .body(Body::from(serde_json::to_string(&create_request).unwrap()))
        .unwrap();

    let response = app.clone().oneshot(request).await.unwrap();
    let body = axum::body::to_bytes(response.into_body(), usize::MAX)
        .await
        .unwrap();
    let create_response: bedrock_sso_proxy::auth::api_key::CreateApiKeyResponse =
        serde_json::from_slice(&body).unwrap();

    let api_key = create_response.key;

    // Test API key authentication
    let api_key_request = Request::builder()
        .uri("/anthropic/v1/messages")
        .method("POST")
        .header("Authorization", format!("Bearer {}", api_key))
        .header("Content-Type", "application/json")
        .body(Body::from(r#"{"model": "claude-sonnet-4-20250514", "max_tokens": 100, "messages": [{"role": "user", "content": "Hello"}]}"#))
        .unwrap();

    let response = app.oneshot(api_key_request).await.unwrap();
    // Should not be unauthorized (would get 401 if API key auth failed)
    assert_ne!(response.status(), StatusCode::UNAUTHORIZED);
}
